spring:
  profiles:
    active: testing
    include:
      - email
      - resources

  liquibase:
    contexts: testing

platform.name: RealMarket

logging:
  level:
    org.springframework.*: info
    io.realmarket.propeler.*: info