server:
  servlet:
    context-path: /api

spring:
  profiles.active: development
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    port: 587
    protocol: smtp
    test-connection: false
    properties:
      mail.smtp:
        auth: true
        starttls.enable: true
    thymeleaf:
      mode: LEGACYHTML5
      cache: false
      view-names: userWildcardsPdf

  jpa: #hibernate
    hibernate.ddl-auto: none
    # Disable feature detection by this undocumented parameter. Check the org.hibernate.engine.jdbc.internal.JdbcServiceImpl.configure method for more details.
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    # Because detection is disabled you have to set correct dialect by hand.
    database-platform=: org.hibernate.dialect.PostgreSQL9Dialect
  datasource:
    url: jdbc:postgresql://${POSTGRESQL_HOST}:${POSTGRESQL_PORT}/${POSTGRESQL_DB}
    username: ${POSTGRESQL_USERNAME}
    password: ${POSTGRESQL_PASSWORD}

cos:
  file_prefix:
    user_picture: user_picture/
    company_featured_image: company_featured_image/
    company_logo: company_logo/
    campaign_market_image: campaign_market_image/
    campaign_investor_picture: campaign_investor_picture/
    campaign_topic_image: local/campaign_topic_image/
  api.key.id: ${COS_API_KEY}
  service.crn: ${COS_SERVICE_CRN}
  endpoint: ${COS_ENDPOINT}
  auth.endpoint: https://iam.ng.bluemix.net/oidc/token
  bucket:
    location: ${COS_BUCKET_LOCATION}
    name: ${COS_BUCKET_NAME}

frontend.service.url: ${FRONTEND_URL_PATH}
hmac.secret: ${HMAC_SECRET}
access-token.expiration-time: 3600000


logging:
  level:
    liquibase: info
    org.springframework.*: info
    io.realmarket.propeler.*: trace
    org.hibernate.SQL: debug

app:
  email:
    contact_us: support@realmarket.io
  scheduler-pool-size: 5
  cleanse:
    tokens.timeloop: 86400000 #24h
    cookies.timeloop: 86400000 #24h
  remember_me.expiration: 2592000000 #30d * 24h * 60m * 60s * 1000ms
  otp:
    secret.size: 16
    wildcard:
      size: 12
      batch_size: 10
  filename-length: 32

  login:
    ip:
      ban:
        attempts: 5
        time-banned: 5
    username:
      ban:
        attempts: 3
        time-banned: 3
        
  registration-captcha:
    ban:
      attempts: 5
      time-banned: 240

google:
  recaptcha:
    secret: ${GOOGLE_RECAPTCHA_SECRET}
reports:
  template-names:
    user-wildcards-pdf: userWildcardsPdf
