email:
  contact_us: support@realmarket.io

  template:
    user:
      register: emails/activateAccountTemplate
      reset_password: emails/resetPasswordTemplate
      recover_username: emails/recoverUsernameTemplate
      change_email: emails/requestEmailChangeTemplate
      secret_change: emails/secretChangeTemplate
      account_blocked: emails/accountBlockedTemplate

    campaign:
      new_opportunity: emails/newCampaignOpportunityTemplate
      new_opportunities: emails/newCampaignOpportunitiesTemplate

      fundraising_proposal_approval: emails/acceptFundraisingProposalTemplate
      fundraising_proposal_rejection: emails/rejectFundraisingProposalTemplate

      approval: emails/acceptCampaignTemplate
      rejection: emails/rejectCampaignTemplate

    kyc:
      under_review: emails/underReviewKYCTemplate
      approval: emails/acceptKYCTemplate
      rejection: emails/rejectKYCTemplate

    investment:
      approval: emails/acceptCampaignInvestmentTemplate
      rejection: emails/rejectCampaignInvestmentTemplate
      proforma_invoice: emails/proformaInvoiceTemplate
      invoice: emails/invoiceTemplate
