spring:
  profiles:
    active: production
    include:
      - email
      - resources
  liquibase:
    contexts: production

logging:
  level:
    org.springframework.*: info
    io.realmarket.propeler.*: info