server:
  servlet:
    context-path: /api

spring:
  profiles.active: local
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:postgresql://localhost:5432/propeler
    username: postgres
    password: mysecretpassword

  jpa:
    hibernate.ddl-auto: none
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect

  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: service@realmarket.io
    password: 12kl3jedkjsajjKAHAS1213
    port: 587
    protocol: smtp
    test-connection: false
    properties:
      mail.smtp:
        auth: true
        starttls.enable: true

frontend.service.url: http://localhost:3000
hmac.secret: s3cr3t
access-token.expiration-time: 3600000
app:
  scheduler-pool-size: 5
  cleanse.tokens:
    timeloop: 86400000 #24h
cos:
  file_prefix:
    user_picture: user_picture/
  api.key.id: MChcbyspqfz11w3SXCwq7HNf43juW7zpIqviRmBaZrni
  service.crn: crn:v1:bluemix:public:iam-identity::a/e5d5a8d969c24db5b8173d0fbd8059ad::serviceid:ServiceId-b736aca2-13a6-4bd3-917f-fc8a27d56187
  endpoint: s3.eu-de.objectstorage.softlayer.net
  auth.endpoint: https://iam.ng.bluemix.net/oidc/token
  bucket:
    location: eu-de
    name: mvp-bucket