server:
  servlet:
    context-path: /api

platform.name: RealMarket

spring:
  profiles:
    active: local
    include:
      - email
      - resource

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:postgresql://localhost:5432/propeler
    username: postgres
    password: mysecretpassword

  jpa:
    hibernate.ddl-auto: none
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect

  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: service@realmarket.io
    password: 12kl3jedkjsajjKAHAS1213
    port: 587
    protocol: smtp
    test-connection: false
    properties:
      mail.smtp:
        from: no-reply
        auth: true
        starttls.enable: true
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  liquibase:
    contexts: local

frontend.service.url: http://localhost:3000
hmac.secret: s3cr3t
access-token.expiration-time: 3600000
registration-token.expiration-time: 604800000
app:
  platformName: RealMarket
  scheduler-pool-size: 5
  cleanse:
    tokens.timeloop: 86400000 #24h
    cookies.timeloop: 86400000 #24h
  remember_me.expiration: 2592000000 #30d * 24h * 60m * 60s * 1000ms
  otp:
    secret.size: 16
    wildcard:
      size: 12
      batch_size: 10
  filename-length: 32
  login:
    ip:
      ban:
        attempts: 5
        time-banned: 5
    username:
      ban:
        attempts: 3
        time-banned: 3

  registration-captcha:
    ban:
      time-banned: 5
      attempts: 5

  investment:
    minimum: 500
    weekInMillis: 604800000

  locale:
    language: de
    country: DE
    timezone: Europe/Belgrade
    currency:
      code: EUR

  bank:
    account-number: 160-24524924592-44
    mod: 97
    name: Srbska banka
    IBAN: 12349876
    SWIFT: 67894321

  payment:
    card-limit: 15000
    VAT: 0.2

cos:
  public_prefix: local_public
  file_prefix:
    user_picture: local/user_picture/
    company_featured_image: local/company_featured_image/
    company_logo: local/company_logo/
    campaign_market_image: local/campaign_market_image/
    shareholder_picture: local/shareholder_picture/
    campaign_team_member_picture: local/campaign_team_member_picture/
    campaign_topic_image: local/campaign_topic_image/
  api.key.id: MChcbyspqfz11w3SXCwq7HNf43juW7zpIqviRmBaZrni
  service.crn: crn:v1:bluemix:public:iam-identity::a/e5d5a8d969c24db5b8173d0fbd8059ad::serviceid:ServiceId-b736aca2-13a6-4bd3-917f-fc8a27d56187
  endpoint: s3.eu-de.objectstorage.softlayer.net
  auth.endpoint: https://iam.ng.bluemix.net/oidc/token
  bucket:
    location: eu-de
    name: mvp-bucket
google:
  recaptcha:
    secret: 6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe

blockchain:
  active: false
  user:
    organization: Org1
  address: http://localhost:5000
  invocation:
    peers: peer0.org1.example.com
    method: fcn
    arguments: args
  chaincode_name: mycc
  channel_name: mychannel

payPal:
  client-id: ARPDjavo9_Oj8ZEZABvlfV28LRH5veb-3WdLaD7ypL7XoK7tKCnYTIv_MRiUigymEJSiNdI-EA_du7Ud
  client-secret: EPFpWXTWi6myPKsfabHi8cNlvUKK75Xmh4aoDBfMUwvWezm5Zn42U8yio40vdwha11-ujFgx0SDAUb-k

logging:
  level:
    liquibase: info
    org.springframework.*: info
    io.realmarket.propeler.*: trace
    org.hibernate.SQL: debug
