-- country
INSERT INTO public.country (code, name) VALUES ('AF', 'Afghanistan');
INSERT INTO public.country (code, name) VALUES ('AX', 'land Islands');
INSERT INTO public.country (code, name) VALUES ('AL', 'Albania');
INSERT INTO public.country (code, name) VALUES ('DZ', 'Algeria');
INSERT INTO public.country (code, name) VALUES ('AS', 'American Samoa');
INSERT INTO public.country (code, name) VALUES ('AD', 'AndorrA');
INSERT INTO public.country (code, name) VALUES ('AO', 'Angola');
INSERT INTO public.country (code, name) VALUES ('AI', 'Anguilla');
INSERT INTO public.country (code, name) VALUES ('AQ', 'Antarctica');
INSERT INTO public.country (code, name) VALUES ('AG', 'Antigua and Barbuda');
INSERT INTO public.country (code, name) VALUES ('AR', 'Argentina');
INSERT INTO public.country (code, name) VALUES ('AM', 'Armenia');
INSERT INTO public.country (code, name) VALUES ('AW', 'Aruba');
INSERT INTO public.country (code, name) VALUES ('AU', 'Australia');
INSERT INTO public.country (code, name) VALUES ('AT', 'Austria');
INSERT INTO public.country (code, name) VALUES ('AZ', 'Azerbaijan');
INSERT INTO public.country (code, name) VALUES ('BS', 'Bahamas');
INSERT INTO public.country (code, name) VALUES ('BH', 'Bahrain');
INSERT INTO public.country (code, name) VALUES ('BD', 'Bangladesh');
INSERT INTO public.country (code, name) VALUES ('BB', 'Barbados');
INSERT INTO public.country (code, name) VALUES ('BY', 'Belarus');
INSERT INTO public.country (code, name) VALUES ('BE', 'Belgium');
INSERT INTO public.country (code, name) VALUES ('BZ', 'Belize');
INSERT INTO public.country (code, name) VALUES ('BJ', 'Benin');
INSERT INTO public.country (code, name) VALUES ('BM', 'Bermuda');
INSERT INTO public.country (code, name) VALUES ('BT', 'Bhutan');
INSERT INTO public.country (code, name) VALUES ('BO', 'Bolivia');
INSERT INTO public.country (code, name) VALUES ('BA', 'Bosnia and Herzegovina');
INSERT INTO public.country (code, name) VALUES ('BW', 'Botswana');
INSERT INTO public.country (code, name) VALUES ('BV', 'Bouvet Island');
INSERT INTO public.country (code, name) VALUES ('BR', 'Brazil');
INSERT INTO public.country (code, name) VALUES ('IO', 'British Indian Ocean Territory');
INSERT INTO public.country (code, name) VALUES ('BN', 'Brunei Darussalam');
INSERT INTO public.country (code, name) VALUES ('BG', 'Bulgaria');
INSERT INTO public.country (code, name) VALUES ('BF', 'Burkina Faso');
INSERT INTO public.country (code, name) VALUES ('BI', 'Burundi');
INSERT INTO public.country (code, name) VALUES ('KH', 'Cambodia');
INSERT INTO public.country (code, name) VALUES ('CM', 'Cameroon');
INSERT INTO public.country (code, name) VALUES ('CA', 'Canada');
INSERT INTO public.country (code, name) VALUES ('CV', 'Cape Verde');
INSERT INTO public.country (code, name) VALUES ('KY', 'Cayman Islands');
INSERT INTO public.country (code, name) VALUES ('CF', 'Central African Republic');
INSERT INTO public.country (code, name) VALUES ('TD', 'Chad');
INSERT INTO public.country (code, name) VALUES ('CL', 'Chile');
INSERT INTO public.country (code, name) VALUES ('CN', 'China');
INSERT INTO public.country (code, name) VALUES ('CX', 'Christmas Island');
INSERT INTO public.country (code, name) VALUES ('CC', 'Cocos (Keeling) Islands');
INSERT INTO public.country (code, name) VALUES ('CO', 'Colombia');
INSERT INTO public.country (code, name) VALUES ('KM', 'Comoros');
INSERT INTO public.country (code, name) VALUES ('CG', 'Congo');
INSERT INTO public.country (code, name) VALUES ('CD', 'Congo, The Democratic Republic of the');
INSERT INTO public.country (code, name) VALUES ('CK', 'Cook Islands');
INSERT INTO public.country (code, name) VALUES ('CR', 'Costa Rica');
INSERT INTO public.country (code, name) VALUES ('CI', 'Cote ''Ivoire');
INSERT INTO public.country (code, name) VALUES ('HR', 'Croatia');
INSERT INTO public.country (code, name) VALUES ('CU', 'Cuba');
INSERT INTO public.country (code, name) VALUES ('CY', 'Cyprus');
INSERT INTO public.country (code, name) VALUES ('CZ', 'Czech Republic');
INSERT INTO public.country (code, name) VALUES ('DK', 'Denmark');
INSERT INTO public.country (code, name) VALUES ('DJ', 'Djibouti');
INSERT INTO public.country (code, name) VALUES ('DM', 'Dominica');
INSERT INTO public.country (code, name) VALUES ('DO', 'Dominican Republic');
INSERT INTO public.country (code, name) VALUES ('EC', 'Ecuador');
INSERT INTO public.country (code, name) VALUES ('EG', 'Egypt');
INSERT INTO public.country (code, name) VALUES ('SV', 'El Salvador');
INSERT INTO public.country (code, name) VALUES ('GQ', 'Equatorial Guinea');
INSERT INTO public.country (code, name) VALUES ('ER', 'Eritrea');
INSERT INTO public.country (code, name) VALUES ('EE', 'Estonia');
INSERT INTO public.country (code, name) VALUES ('ET', 'Ethiopia');
INSERT INTO public.country (code, name) VALUES ('FK', 'Falkland Islands (Malvinas)');
INSERT INTO public.country (code, name) VALUES ('FO', 'Faroe Islands');
INSERT INTO public.country (code, name) VALUES ('FJ', 'Fiji');
INSERT INTO public.country (code, name) VALUES ('FI', 'Finland');
INSERT INTO public.country (code, name) VALUES ('FR', 'France');
INSERT INTO public.country (code, name) VALUES ('GF', 'French Guiana');
INSERT INTO public.country (code, name) VALUES ('PF', 'French Polynesia');
INSERT INTO public.country (code, name) VALUES ('TF', 'French Southern Territories');
INSERT INTO public.country (code, name) VALUES ('GA', 'Gabon');
INSERT INTO public.country (code, name) VALUES ('GM', 'Gambia');
INSERT INTO public.country (code, name) VALUES ('GE', 'Georgia');
INSERT INTO public.country (code, name) VALUES ('DE', 'Germany');
INSERT INTO public.country (code, name) VALUES ('GH', 'Ghana');
INSERT INTO public.country (code, name) VALUES ('GI', 'Gibraltar');
INSERT INTO public.country (code, name) VALUES ('GR', 'Greece');
INSERT INTO public.country (code, name) VALUES ('GL', 'Greenland');
INSERT INTO public.country (code, name) VALUES ('GD', 'Grenada');
INSERT INTO public.country (code, name) VALUES ('GP', 'Guadeloupe');
INSERT INTO public.country (code, name) VALUES ('GU', 'Guam');
INSERT INTO public.country (code, name) VALUES ('GT', 'Guatemala');
INSERT INTO public.country (code, name) VALUES ('GG', 'Guernsey');
INSERT INTO public.country (code, name) VALUES ('GN', 'Guinea');
INSERT INTO public.country (code, name) VALUES ('GW', 'Guinea-Bissau');
INSERT INTO public.country (code, name) VALUES ('GY', 'Guyana');
INSERT INTO public.country (code, name) VALUES ('HT', 'Haiti');
INSERT INTO public.country (code, name) VALUES ('HM', 'Heard Island and Mcdonald Islands');
INSERT INTO public.country (code, name) VALUES ('VA', 'Holy See (Vatican City State)');
INSERT INTO public.country (code, name) VALUES ('HN', 'Honduras');
INSERT INTO public.country (code, name) VALUES ('HK', 'Hong Kong');
INSERT INTO public.country (code, name) VALUES ('HU', 'Hungary');
INSERT INTO public.country (code, name) VALUES ('IS', 'Iceland');
INSERT INTO public.country (code, name) VALUES ('IN', 'India');
INSERT INTO public.country (code, name) VALUES ('ID', 'Indonesia');
INSERT INTO public.country (code, name) VALUES ('IR', 'Iran, Islamic Republic Of');
INSERT INTO public.country (code, name) VALUES ('IQ', 'Iraq');
INSERT INTO public.country (code, name) VALUES ('IE', 'Ireland');
INSERT INTO public.country (code, name) VALUES ('IM', 'Isle of Man');
INSERT INTO public.country (code, name) VALUES ('IL', 'Israel');
INSERT INTO public.country (code, name) VALUES ('IT', 'Italy');
INSERT INTO public.country (code, name) VALUES ('JM', 'Jamaica');
INSERT INTO public.country (code, name) VALUES ('JP', 'Japan');
INSERT INTO public.country (code, name) VALUES ('JE', 'Jersey');
INSERT INTO public.country (code, name) VALUES ('JO', 'Jordan');
INSERT INTO public.country (code, name) VALUES ('KZ', 'Kazakhstan');
INSERT INTO public.country (code, name) VALUES ('KE', 'Kenya');
INSERT INTO public.country (code, name) VALUES ('KI', 'Kiribati');
INSERT INTO public.country (code, name) VALUES ('KP', 'Korea, Democratic People''S Republic of');
INSERT INTO public.country (code, name) VALUES ('KR', 'Korea, Republic of');
INSERT INTO public.country (code, name) VALUES ('KW', 'Kuwait');
INSERT INTO public.country (code, name) VALUES ('KG', 'Kyrgyzstan');
INSERT INTO public.country (code, name) VALUES ('LA', 'Lao People''S Democratic Republic');
INSERT INTO public.country (code, name) VALUES ('LV', 'Latvia');
INSERT INTO public.country (code, name) VALUES ('LB', 'Lebanon');
INSERT INTO public.country (code, name) VALUES ('LS', 'Lesotho');
INSERT INTO public.country (code, name) VALUES ('LR', 'Liberia');
INSERT INTO public.country (code, name) VALUES ('LY', 'Libyan Arab Jamahiriya');
INSERT INTO public.country (code, name) VALUES ('LI', 'Liechtenstein');
INSERT INTO public.country (code, name) VALUES ('LT', 'Lithuania');
INSERT INTO public.country (code, name) VALUES ('LU', 'Luxembourg');
INSERT INTO public.country (code, name) VALUES ('MO', 'Macao');
INSERT INTO public.country (code, name) VALUES ('MK', 'Macedonia, The Former Yugoslav Republic of');
INSERT INTO public.country (code, name) VALUES ('MG', 'Madagascar');
INSERT INTO public.country (code, name) VALUES ('MW', 'Malawi');
INSERT INTO public.country (code, name) VALUES ('MY', 'Malaysia');
INSERT INTO public.country (code, name) VALUES ('MV', 'Maldives');
INSERT INTO public.country (code, name) VALUES ('ML', 'Mali');
INSERT INTO public.country (code, name) VALUES ('MT', 'Malta');
INSERT INTO public.country (code, name) VALUES ('MH', 'Marshall Islands');
INSERT INTO public.country (code, name) VALUES ('MQ', 'Martinique');
INSERT INTO public.country (code, name) VALUES ('MR', 'Mauritania');
INSERT INTO public.country (code, name) VALUES ('MU', 'Mauritius');
INSERT INTO public.country (code, name) VALUES ('YT', 'Mayotte');
INSERT INTO public.country (code, name) VALUES ('MX', 'Mexico');
INSERT INTO public.country (code, name) VALUES ('FM', 'Micronesia, Federated States of');
INSERT INTO public.country (code, name) VALUES ('MD', 'Moldova, Republic of');
INSERT INTO public.country (code, name) VALUES ('MC', 'Monaco');
INSERT INTO public.country (code, name) VALUES ('MN', 'Mongolia');
INSERT INTO public.country (code, name) VALUES ('ME', 'Montenegro');
INSERT INTO public.country (code, name) VALUES ('MS', 'Montserrat');
INSERT INTO public.country (code, name) VALUES ('MA', 'Morocco');
INSERT INTO public.country (code, name) VALUES ('MZ', 'Mozambique');
INSERT INTO public.country (code, name) VALUES ('MM', 'Myanmar');
INSERT INTO public.country (code, name) VALUES ('NA', 'Namibia');
INSERT INTO public.country (code, name) VALUES ('NR', 'Nauru');
INSERT INTO public.country (code, name) VALUES ('NP', 'Nepal');
INSERT INTO public.country (code, name) VALUES ('NL', 'Netherlands');
INSERT INTO public.country (code, name) VALUES ('AN', 'Netherlands Antilles');
INSERT INTO public.country (code, name) VALUES ('NC', 'New Caledonia');
INSERT INTO public.country (code, name) VALUES ('NZ', 'New Zealand');
INSERT INTO public.country (code, name) VALUES ('NI', 'Nicaragua');
INSERT INTO public.country (code, name) VALUES ('NE', 'Niger');
INSERT INTO public.country (code, name) VALUES ('NG', 'Nigeria');
INSERT INTO public.country (code, name) VALUES ('NU', 'Niue');
INSERT INTO public.country (code, name) VALUES ('NF', 'Norfolk Island');
INSERT INTO public.country (code, name) VALUES ('MP', 'Northern Mariana Islands');
INSERT INTO public.country (code, name) VALUES ('NO', 'Norway');
INSERT INTO public.country (code, name) VALUES ('OM', 'Oman');
INSERT INTO public.country (code, name) VALUES ('PK', 'Pakistan');
INSERT INTO public.country (code, name) VALUES ('PW', 'Palau');
INSERT INTO public.country (code, name) VALUES ('PS', 'Palestinian Territory, Occupied');
INSERT INTO public.country (code, name) VALUES ('PA', 'Panama');
INSERT INTO public.country (code, name) VALUES ('PG', 'Papua New Guinea');
INSERT INTO public.country (code, name) VALUES ('PY', 'Paraguay');
INSERT INTO public.country (code, name) VALUES ('PE', 'Peru');
INSERT INTO public.country (code, name) VALUES ('PH', 'Philippines');
INSERT INTO public.country (code, name) VALUES ('PN', 'Pitcairn');
INSERT INTO public.country (code, name) VALUES ('PL', 'Poland');
INSERT INTO public.country (code, name) VALUES ('PT', 'Portugal');
INSERT INTO public.country (code, name) VALUES ('PR', 'Puerto Rico');
INSERT INTO public.country (code, name) VALUES ('QA', 'Qatar');
INSERT INTO public.country (code, name) VALUES ('RE', 'Reunion');
INSERT INTO public.country (code, name) VALUES ('RO', 'Romania');
INSERT INTO public.country (code, name) VALUES ('RU', 'Russian Federation');
INSERT INTO public.country (code, name) VALUES ('RW', 'RWANDA');
INSERT INTO public.country (code, name) VALUES ('SH', 'Saint Helena');
INSERT INTO public.country (code, name) VALUES ('KN', 'Saint Kitts and Nevis');
INSERT INTO public.country (code, name) VALUES ('LC', 'Saint Lucia');
INSERT INTO public.country (code, name) VALUES ('PM', 'Saint Pierre and Miquelon');
INSERT INTO public.country (code, name) VALUES ('VC', 'Saint Vincent and the Grenadines');
INSERT INTO public.country (code, name) VALUES ('WS', 'Samoa');
INSERT INTO public.country (code, name) VALUES ('SM', 'San Marino');
INSERT INTO public.country (code, name) VALUES ('ST', 'Sao Tome and Principe');
INSERT INTO public.country (code, name) VALUES ('SA', 'Saudi Arabia');
INSERT INTO public.country (code, name) VALUES ('SN', 'Senegal');
INSERT INTO public.country (code, name) VALUES ('RS', 'Serbia');
INSERT INTO public.country (code, name) VALUES ('SC', 'Seychelles');
INSERT INTO public.country (code, name) VALUES ('SL', 'Sierra Leone');
INSERT INTO public.country (code, name) VALUES ('SG', 'Singapore');
INSERT INTO public.country (code, name) VALUES ('SK', 'Slovakia');
INSERT INTO public.country (code, name) VALUES ('SI', 'Slovenia');
INSERT INTO public.country (code, name) VALUES ('SB', 'Solomon Islands');
INSERT INTO public.country (code, name) VALUES ('SO', 'Somalia');
INSERT INTO public.country (code, name) VALUES ('ZA', 'South Africa');
INSERT INTO public.country (code, name) VALUES ('GS', 'South Georgia and the South Sandwich Islands');
INSERT INTO public.country (code, name) VALUES ('ES', 'Spain');
INSERT INTO public.country (code, name) VALUES ('LK', 'Sri Lanka');
INSERT INTO public.country (code, name) VALUES ('SD', 'Sudan');
INSERT INTO public.country (code, name) VALUES ('SR', 'Surilabel');
INSERT INTO public.country (code, name) VALUES ('SJ', 'Svalbard and Jan Mayen');
INSERT INTO public.country (code, name) VALUES ('SZ', 'Swaziland');
INSERT INTO public.country (code, name) VALUES ('SE', 'Sweden');
INSERT INTO public.country (code, name) VALUES ('CH', 'Switzerland');
INSERT INTO public.country (code, name) VALUES ('SY', 'Syrian Arab Republic');
INSERT INTO public.country (code, name) VALUES ('TW', 'Taiwan, Province of China');
INSERT INTO public.country (code, name) VALUES ('TJ', 'Tajikistan');
INSERT INTO public.country (code, name) VALUES ('TZ', 'Tanzania, United Republic of');
INSERT INTO public.country (code, name) VALUES ('TH', 'Thailand');
INSERT INTO public.country (code, name) VALUES ('TL', 'Timor-Leste');
INSERT INTO public.country (code, name) VALUES ('TG', 'Togo');
INSERT INTO public.country (code, name) VALUES ('TK', 'Tokelau');
INSERT INTO public.country (code, name) VALUES ('TO', 'Tonga');
INSERT INTO public.country (code, name) VALUES ('TT', 'Trinidad and Tobago');
INSERT INTO public.country (code, name) VALUES ('TN', 'Tunisia');
INSERT INTO public.country (code, name) VALUES ('TR', 'Turkey');
INSERT INTO public.country (code, name) VALUES ('TM', 'Turkmenistan');
INSERT INTO public.country (code, name) VALUES ('TC', 'Turks and Caicos Islands');
INSERT INTO public.country (code, name) VALUES ('TV', 'Tuvalu');
INSERT INTO public.country (code, name) VALUES ('UG', 'Uganda');
INSERT INTO public.country (code, name) VALUES ('UA', 'Ukraine');
INSERT INTO public.country (code, name) VALUES ('AE', 'United Arab Emirates');
INSERT INTO public.country (code, name) VALUES ('GB', 'United Kingdom');
INSERT INTO public.country (code, name) VALUES ('US', 'United States');
INSERT INTO public.country (code, name) VALUES ('UM', 'United States Minor Outlying Islands');
INSERT INTO public.country (code, name) VALUES ('UY', 'Uruguay');
INSERT INTO public.country (code, name) VALUES ('UZ', 'Uzbekistan');
INSERT INTO public.country (code, name) VALUES ('VU', 'Vanuatu');
INSERT INTO public.country (code, name) VALUES ('VE', 'Venezuela');
INSERT INTO public.country (code, name) VALUES ('VN', 'Viet Nam');
INSERT INTO public.country (code, name) VALUES ('VG', 'Virgin Islands, British');
INSERT INTO public.country (code, name) VALUES ('VI', 'Virgin Islands, U.S.');
INSERT INTO public.country (code, name) VALUES ('WF', 'Wallis and Futuna');
INSERT INTO public.country (code, name) VALUES ('EH', 'Western Sahara');
INSERT INTO public.country (code, name) VALUES ('YE', 'Yemen');
INSERT INTO public.country (code, name) VALUES ('ZM', 'Zambia');
INSERT INTO public.country (code, name) VALUES ('ZW', 'Zimbabwe');

-- auth state
INSERT INTO public.auth_state (id, name) VALUES (NEXTVAL('auth_state_seq'), 'CONFIRM_REGISTRATION');
INSERT INTO public.auth_state (id, name) VALUES (NEXTVAL('auth_state_seq'), 'INITIALIZE_2FA');
INSERT INTO public.auth_state (id, name) VALUES (NEXTVAL('auth_state_seq'), 'ACTIVE');

-- authorized action type
INSERT INTO public.authorized_action_type (id, name) VALUES (NEXTVAL('authorized_action_type_seq'), 'NEW_TOTP_SECRET');
INSERT INTO public.authorized_action_type (id, name) VALUES (NEXTVAL('authorized_action_type_seq'), 'NEW_PASSWORD');
INSERT INTO public.authorized_action_type (id, name) VALUES (NEXTVAL('authorized_action_type_seq'), 'NEW_EMAIL');

-- temporary token type
INSERT INTO public.temporary_token_type (id, name) VALUES (NEXTVAL('temporary_token_type_seq'), 'SETUP_2FA_TOKEN');
INSERT INTO public.temporary_token_type (id, name) VALUES (NEXTVAL('temporary_token_type_seq'), 'LOGIN_TOKEN');
INSERT INTO public.temporary_token_type (id, name) VALUES (NEXTVAL('temporary_token_type_seq'), 'REGISTRATION_TOKEN');
INSERT INTO public.temporary_token_type (id, name) VALUES (NEXTVAL('temporary_token_type_seq'), 'EMAIL_TOKEN');
INSERT INTO public.temporary_token_type (id, name) VALUES (NEXTVAL('temporary_token_type_seq'), 'RESET_PASSWORD_TOKEN');
INSERT INTO public.temporary_token_type (id, name) VALUES (NEXTVAL('temporary_token_type_seq'), 'EMAIL_CHANGE_TOKEN');
INSERT INTO public.temporary_token_type (id, name) VALUES (NEXTVAL('temporary_token_type_seq'), 'PASSWORD_VERIFIED_TOKEN');

-- user role
INSERT INTO public.user_role (id, name) VALUES (NEXTVAL('user_role_seq'), 'ROLE_ADMIN');
INSERT INTO public.user_role (id, name) VALUES (NEXTVAL('user_role_seq'), 'ROLE_INDIVIDUAL_INVESTOR');
INSERT INTO public.user_role (id, name) VALUES (NEXTVAL('user_role_seq'), 'ROLE_CORPORATE_INVESTOR');
INSERT INTO public.user_role (id, name) VALUES (NEXTVAL('user_role_seq'), 'ROLE_ENTREPRENEUR');

-- company category
INSERT INTO public.company_category (id, name) VALUES (NEXTVAL('company_category_seq'), 'Agriculture');
INSERT INTO public.company_category (id, name) VALUES (NEXTVAL('company_category_seq'), 'Big Data & AI');
INSERT INTO public.company_category (id, name) VALUES (NEXTVAL('company_category_seq'), 'Biotech and Medicine');
INSERT INTO public.company_category (id, name) VALUES (NEXTVAL('company_category_seq'), 'Blockchain & Cryptocurrencies');
INSERT INTO public.company_category (id, name) VALUES (NEXTVAL('company_category_seq'), 'Cyber Security');
INSERT INTO public.company_category (id, name) VALUES (NEXTVAL('company_category_seq'), 'Design & Graphics');
INSERT INTO public.company_category (id, name) VALUES (NEXTVAL('company_category_seq'), 'eCommerce');
INSERT INTO public.company_category (id, name) VALUES (NEXTVAL('company_category_seq'), 'Education');
INSERT INTO public.company_category (id, name) VALUES (NEXTVAL('company_category_seq'), 'Energy & Sustainability');
INSERT INTO public.company_category (id, name) VALUES (NEXTVAL('company_category_seq'), 'Fashion');
INSERT INTO public.company_category (id, name) VALUES (NEXTVAL('company_category_seq'), 'Financial Services');
INSERT INTO public.company_category (id, name) VALUES (NEXTVAL('company_category_seq'), 'Food & Drinks');
INSERT INTO public.company_category (id, name) VALUES (NEXTVAL('company_category_seq'), 'Gaming');
INSERT INTO public.company_category (id, name) VALUES (NEXTVAL('company_category_seq'), 'Hardware');
INSERT INTO public.company_category (id, name) VALUES (NEXTVAL('company_category_seq'), 'Health & Fitness');
INSERT INTO public.company_category (id, name) VALUES (NEXTVAL('company_category_seq'), 'Human Resources');
INSERT INTO public.company_category (id, name) VALUES (NEXTVAL('company_category_seq'), 'Insurance');
INSERT INTO public.company_category (id, name) VALUES (NEXTVAL('company_category_seq'), 'IoT (The Internet of Things)');
INSERT INTO public.company_category (id, name) VALUES (NEXTVAL('company_category_seq'), 'Legal Services');
INSERT INTO public.company_category (id, name) VALUES (NEXTVAL('company_category_seq'), 'Marketing & Advertising');
INSERT INTO public.company_category (id, name) VALUES (NEXTVAL('company_category_seq'), 'Media & Communication');
INSERT INTO public.company_category (id, name) VALUES (NEXTVAL('company_category_seq'), 'Mobility & Logistics');
INSERT INTO public.company_category (id, name) VALUES (NEXTVAL('company_category_seq'), 'Music');
INSERT INTO public.company_category (id, name) VALUES (NEXTVAL('company_category_seq'), 'Real Estate');
INSERT INTO public.company_category (id, name) VALUES (NEXTVAL('company_category_seq'), 'Sharing & Gig Economy (Rent Services to the Companies)');
INSERT INTO public.company_category (id, name) VALUES (NEXTVAL('company_category_seq'), 'Social Media & Events');
INSERT INTO public.company_category (id, name) VALUES (NEXTVAL('company_category_seq'), 'Travel');
INSERT INTO public.company_category (id, name) VALUES (NEXTVAL('company_category_seq'), 'Video & Photography');
INSERT INTO public.company_category (id, name) VALUES (NEXTVAL('company_category_seq'), 'Virtual & Augmented Reality');

-- campaign state
INSERT INTO public.campaign_state (id, name) VALUES (NEXTVAL('campaign_state_seq'), 'INITIAL');
INSERT INTO public.campaign_state (id, name) VALUES (NEXTVAL('campaign_state_seq'), 'REVIEW_READY');
INSERT INTO public.campaign_state (id, name) VALUES (NEXTVAL('campaign_state_seq'), 'AUDIT');
INSERT INTO public.campaign_state (id, name) VALUES (NEXTVAL('campaign_state_seq'), 'FINANCE_PROPOSITION');
INSERT INTO public.campaign_state (id, name) VALUES (NEXTVAL('campaign_state_seq'), 'LEAD_INVESTMENT');
INSERT INTO public.campaign_state (id, name) VALUES (NEXTVAL('campaign_state_seq'), 'ACTIVE');
INSERT INTO public.campaign_state (id, name) VALUES (NEXTVAL('campaign_state_seq'), 'POST_CAMPAIGN');
INSERT INTO public.campaign_state (id, name) VALUES (NEXTVAL('campaign_state_seq'), 'DELETED');

-- request state
INSERT INTO public.request_state (id, name) VALUES (NEXTVAL('request_state_seq'), 'PENDING');
INSERT INTO public.request_state (id, name) VALUES (NEXTVAL('request_state_seq'), 'APPROVED');
INSERT INTO public.request_state (id, name) VALUES (NEXTVAL('request_state_seq'), 'DECLINED');

-- investment state
INSERT INTO public.investment_state (id, name) VALUES (NEXTVAL('investment_state_seq'), 'INITIAL');
INSERT INTO public.investment_state (id, name) VALUES (NEXTVAL('investment_state_seq'), 'OWNER_APPROVED');
INSERT INTO public.investment_state (id, name) VALUES (NEXTVAL('investment_state_seq'), 'OWNER_REJECTED');
INSERT INTO public.investment_state (id, name) VALUES (NEXTVAL('investment_state_seq'), 'PAID');
INSERT INTO public.investment_state (id, name) VALUES (NEXTVAL('investment_state_seq'), 'EXPIRED');
INSERT INTO public.investment_state (id, name) VALUES (NEXTVAL('investment_state_seq'), 'REVOKED');
INSERT INTO public.investment_state (id, name) VALUES (NEXTVAL('investment_state_seq'), 'AUDIT_APPROVED');
INSERT INTO public.investment_state (id, name) VALUES (NEXTVAL('investment_state_seq'), 'AUDIT_REJECTED');

-- campaign topic type
INSERT INTO public.campaign_topic_type (id, name) VALUES (NEXTVAL('campaign_topic_type_seq'), 'PROBLEM');
INSERT INTO public.campaign_topic_type (id, name) VALUES (NEXTVAL('campaign_topic_type_seq'), 'SOLUTION');
INSERT INTO public.campaign_topic_type (id, name) VALUES (NEXTVAL('campaign_topic_type_seq'), 'RISK_AND_COMPETITION');
INSERT INTO public.campaign_topic_type (id, name) VALUES (NEXTVAL('campaign_topic_type_seq'), 'UPDATES');
INSERT INTO public.campaign_topic_type (id, name) VALUES (NEXTVAL('campaign_topic_type_seq'), 'OVERVIEW');
INSERT INTO public.campaign_topic_type (id, name) VALUES (NEXTVAL('campaign_topic_type_seq'), 'MARKET');
INSERT INTO public.campaign_topic_type (id, name) VALUES (NEXTVAL('campaign_topic_type_seq'), 'TRACTION');

-- document access level
INSERT INTO public.document_access_level (id, name) VALUES (NEXTVAL('document_access_level_seq'), 'PUBLIC');
INSERT INTO public.document_access_level (id, name) VALUES (NEXTVAL('document_access_level_seq'), 'PRIVATE');
INSERT INTO public.document_access_level (id, name) VALUES (NEXTVAL('document_access_level_seq'), 'ON_DEMAND');

-- document type
INSERT INTO public.document_type (id, name) VALUES (NEXTVAL('document_type_seq'), 'DUE_DILIGENCE');
INSERT INTO public.document_type (id, name) VALUES (NEXTVAL('document_type_seq'), 'LEGAL');
INSERT INTO public.document_type (id, name) VALUES (NEXTVAL('document_type_seq'), 'APR_PAPER');
INSERT INTO public.document_type (id, name) VALUES (NEXTVAL('document_type_seq'), 'BUSINESS_PLAN');
INSERT INTO public.document_type (id, name) VALUES (NEXTVAL('document_type_seq'), 'PITCH_DECK');
INSERT INTO public.document_type (id, name) VALUES (NEXTVAL('document_type_seq'), 'BANK');
INSERT INTO public.document_type (id, name) VALUES (NEXTVAL('document_type_seq'), 'USER_KYC');
INSERT INTO public.document_type (id, name) VALUES (NEXTVAL('document_type_seq'), 'CORPORATE_INVESTOR_KYC');
INSERT INTO public.document_type (id, name) VALUES (NEXTVAL('document_type_seq'), 'PAYMENT_PROOF');

-- person
INSERT INTO public.person (id, address, city, country_for_taxation, country_of_residence, email, first_name, last_name, phone_number, profile_picture_url) VALUES (NEXTVAL('person_seq'), 'Modene', 'Novi Sad', null, 'BB', 'marina.nenic@realmarket.io', 'Marina', 'Nenic', null, null);
INSERT INTO public.person (id, address, city, country_for_taxation, country_of_residence, email, first_name, last_name, phone_number, profile_picture_url) VALUES (NEXTVAL('person_seq'), 'Modene 1', 'Novi Sad', 'BS', 'AU', 'angelina.vujanovic@realmarket.io', 'Angelina', 'Vujanovic', null, null);
INSERT INTO public.person (id, address, city, country_for_taxation, country_of_residence, email, first_name, last_name, phone_number, profile_picture_url) VALUES (NEXTVAL('person_seq'), 'Modene', 'Novi Sad', null, 'BB', 'nikola.todorovic@realmarket.io', 'Nikola', 'Todorovic', null, null);
INSERT INTO public.person (id, address, city, country_for_taxation, country_of_residence, email, first_name, last_name, phone_number, profile_picture_url) VALUES (NEXTVAL('person_seq'), 'Modene 1', 'Novi Sad', 'BS', 'AU', 'vladimir.ivkovic@realmarket.io', 'Vladimir', 'Ivkovic', null, null);
INSERT INTO public.person (id, address, city, country_for_taxation, country_of_residence, email, first_name, last_name, phone_number, profile_picture_url) VALUES (NEXTVAL('person_seq'), 'Modene 1', 'Novi Sad', null, 'BB', 'alice.rm@mailinator.com', 'Alice', 'Entrepreneur', null, null);
INSERT INTO public.person (id, address, city, country_for_taxation, country_of_residence, email, first_name, last_name, phone_number, profile_picture_url) VALUES (NEXTVAL('person_seq'), 'Modene 1', 'Novi Sad', 'BS', 'AU', 'ognjen.vlajic@realmarket.io', 'Ginny ', 'Investor', null, null);
INSERT INTO public.person (id, address, city, country_for_taxation, country_of_residence, email, first_name, last_name, phone_number, profile_picture_url) VALUES (NEXTVAL('person_seq'), 'Modene 1', 'Novi Sad', null, 'BB', 'ent.rm@mailinator.com', 'Entepreneur', 'Entrepreneur', null, null);
INSERT INTO public.person (id, address, city, country_for_taxation, country_of_residence, email, first_name, last_name, phone_number, profile_picture_url) VALUES (NEXTVAL('person_seq'), 'Modene 1', 'Novi Sad', null, 'BB', 'ari.rm@mailinator.com', 'Adminiana', 'Grande', null, null);

-- auth
INSERT INTO public.auth (id, state_id, password, user_role_id, blocked, totp_secret, username, person_id) VALUES (NEXTVAL('auth_seq'), 3, '$2a$10$E6Pwa0HnLWOoZIBBuZVyV.TodJ88sb.iBin.U2e9YSp7Z0ZaPXck2', 4, false, 'secret', 'marina', 1);
INSERT INTO public.auth (id, state_id, password, user_role_id, blocked, totp_secret, username, person_id) VALUES (NEXTVAL('auth_seq'), 3, '$2a$10$Nd8uSgyw8fYxUqMNET.TruoaYI.te6D3f5YPVVIm0QqRhzJVCGgma', 4, false, 'secret', 'angelina', 2);
INSERT INTO public.auth (id, state_id, password, user_role_id, blocked, totp_secret, username, person_id) VALUES (NEXTVAL('auth_seq'), 3, '$2a$10$Nd8uSgyw8fYxUqMNET.TruoaYI.te6D3f5YPVVIm0QqRhzJVCGgma', 4, false, 'secret', 'nikola', 3);
INSERT INTO public.auth (id, state_id, password, user_role_id, blocked, totp_secret, username, person_id) VALUES (NEXTVAL('auth_seq'), 3, '$2a$10$E6Pwa0HnLWOoZIBBuZVyV.TodJ88sb.iBin.U2e9YSp7Z0ZaPXck2', 4, false, 'secret', 'vladimir', 4);
/*password is testPASS123 */
INSERT INTO public.auth (id, state_id, password, user_role_id, blocked, totp_secret, username, person_id) VALUES (NEXTVAL('auth_seq'), 3, '$2a$10$nTWQERaNUio88aEHzSVhrOmzsH6XRCfrftpJDxNqwsEdDjh8Y4PFi', 4, false, 'secret', 'entrepreneur', 5);
INSERT INTO public.auth (id, state_id, password, user_role_id, blocked, totp_secret, username, person_id) VALUES (NEXTVAL('auth_seq'), 3, '$2a$10$nTWQERaNUio88aEHzSVhrOmzsH6XRCfrftpJDxNqwsEdDjh8Y4PFi', 2, false, 'secret', 'investor', 6);
INSERT INTO public.auth (id, state_id, password, user_role_id, blocked, totp_secret, username, person_id) VALUES (NEXTVAL('auth_seq'), 3, '$2a$10$nTWQERaNUio88aEHzSVhrOmzsH6XRCfrftpJDxNqwsEdDjh8Y4PFi', 4, false, 'secret', 'entrepreneur2', 7);
INSERT INTO public.auth (id, state_id, password, user_role_id, blocked, totp_secret, username, person_id) VALUES (NEXTVAL('auth_seq'), 3, '$2a$10$nTWQERaNUio88aEHzSVhrOmzsH6XRCfrftpJDxNqwsEdDjh8Y4PFi', 1, false, 'secret', 'admin', 8);


-- used in LoginUtil to login like entrepreneur
INSERT INTO public.remember_me_cookie (id, expiration_time, value, auth_id) VALUES (1, TO_DATE('01/05/2022', 'DD/MM/YYYY'), '1234', 5);

-- used in AuthTest
INSERT INTO public.person (id, address, city, country_for_taxation, country_of_residence, email, first_name, last_name, phone_number, profile_picture_url) VALUES (NEXTVAL('person_seq'), 'Modene 1', 'Novi Sad', null, 'BB', 'test.confirm.registration@mailinator.com', 'Entepreneur', 'Entrepreneur', null, null);
INSERT INTO public.auth (id, state_id, password, user_role_id, blocked, totp_secret, username, person_id) VALUES (NEXTVAL('auth_seq'), 1, '$2a$10$nTWQERaNUio88aEHzSVhrOmzsH6XRCfrftpJDxNqwsEdDjh8Y4PFi', 4, false, 'secret', 'testConfirmRegistration', 9);
INSERT INTO public.temporary_token (id, expiration_time, temporary_token_type_id, value, auth_id) VALUES (NEXTVAL('temporary_token_seq'), TO_DATE('01/05/2050', 'DD/MM/YYYY'), 1, 'verificationToken', 9);
INSERT INTO public.person (id, address, city, country_for_taxation, country_of_residence, email, first_name, last_name, phone_number, profile_picture_url) VALUES (NEXTVAL('person_seq'), 'Modene 1', 'Novi Sad', null, 'BB', 'test.reset.password@mailinator.com', 'Entepreneur', 'Entrepreneur', null, null);
INSERT INTO public.auth (id, state_id, password, user_role_id, blocked, totp_secret, username, person_id) VALUES (NEXTVAL('auth_seq'), 3, '$2a$10$nTWQERaNUio88aEHzSVhrOmzsH6XRCfrftpJDxNqwsEdDjh8Y4PFi', 4, false, 'secret', 'testResetPassword', 10);
INSERT INTO public.person (id, address, city, country_for_taxation, country_of_residence, email, first_name, last_name, phone_number, profile_picture_url) VALUES (NEXTVAL('person_seq'), 'Modene 1', 'Novi Sad', null, 'BB', 'test.reset.password2@mailinator.com', 'Entepreneur', 'Entrepreneur', null, null);
INSERT INTO public.auth (id, state_id, password, user_role_id, blocked, totp_secret, username, person_id) VALUES (NEXTVAL('auth_seq'), 3, '$2a$10$nTWQERaNUio88aEHzSVhrOmzsH6XRCfrftpJDxNqwsEdDjh8Y4PFi', 4, false, 'secret', 'testResetPassword2', 11);
INSERT INTO public.temporary_token (id, expiration_time, temporary_token_type_id, value, auth_id) VALUES (NEXTVAL('temporary_token_seq'), TO_DATE('01/05/2050', 'DD/MM/YYYY'), 5, 'resetPasswordToken', 11);
INSERT INTO public.person (id, address, city, country_for_taxation, country_of_residence, email, first_name, last_name, phone_number, profile_picture_url) VALUES (NEXTVAL('person_seq'), 'Modene 1', 'Novi Sad', null, 'BB', 'test.recover.username@mailinator.com', 'Entepreneur', 'Entrepreneur', null, null);
INSERT INTO public.auth (id, state_id, password, user_role_id, blocked, totp_secret, username, person_id) VALUES (NEXTVAL('auth_seq'), 1, '$2a$10$nTWQERaNUio88aEHzSVhrOmzsH6XRCfrftpJDxNqwsEdDjh8Y4PFi', 4, false, 'secret', 'testRecoverUsername', 12);
INSERT INTO public.person (id, address, city, country_for_taxation, country_of_residence, email, first_name, last_name, phone_number, profile_picture_url) VALUES (NEXTVAL('person_seq'), 'Modene 1', 'Novi Sad', null, 'BB', 'test.confirm.email.change@mailinator.com', 'Entepreneur', 'Entrepreneur', null, null);
INSERT INTO public.auth (id, state_id, password, user_role_id, blocked, totp_secret, username, person_id) VALUES (NEXTVAL('auth_seq'), 3, '$2a$10$nTWQERaNUio88aEHzSVhrOmzsH6XRCfrftpJDxNqwsEdDjh8Y4PFi', 4, false, 'secret', 'testConfirmEmailChange', 13);
INSERT INTO public.temporary_token (id, expiration_time, temporary_token_type_id, value, auth_id) VALUES (NEXTVAL('temporary_token_seq'), TO_DATE('01/05/2050', 'DD/MM/YYYY'), 6, 'confirmEmailChangeToken', 13);
INSERT INTO public.authorized_action (id, auth_id, data, expiration, type_id) VALUES (NEXTVAL('authorized_action_seq'), 13, 'authAction', TO_DATE('01/05/2050', 'DD/MM/YYYY'), 3);

INSERT INTO public.fundraising_proposal (id, first_name, last_name, company_name, website, email, phone_number, previously_raised, funding_goals, rejection_reason, request_state_id) VALUES (NEXTVAL('fundraising_proposal_seq'), 'testFirstName', 'testLastName', 'testCompany', 'testWebsite','test.fundraising1@malinator.com', '+3812122333', '<100K', '100K-500K', null, 1);
INSERT INTO public.registration_token (id, value, expiration_time, fundraising_proposal_id) VALUES (NEXTVAL('registration_token_seq'), 'tokenValue', TO_DATE('01/05/2050', 'DD/MM/YYYY'), 1);
INSERT INTO public.fundraising_proposal (id, first_name, last_name, company_name, website, email, phone_number, previously_raised, funding_goals, rejection_reason, request_state_id) VALUES (NEXTVAL('fundraising_proposal_seq'), 'testFirstName', 'testLastName', 'testCompany', 'testWebsite','test.fundraising1@malinator.com', '+3812122333', '<100K', '100K-500K', null, 1);
INSERT INTO public.registration_token (id, value, expiration_time, fundraising_proposal_id) VALUES (NEXTVAL('registration_token_seq'), 'tokenValidateValue', TO_DATE('01/05/2050', 'DD/MM/YYYY'), 2);

-- used in TwoFactorAuthTest
INSERT INTO public.person (id, address, city, country_for_taxation, country_of_residence, email, first_name, last_name, phone_number, profile_picture_url) VALUES (NEXTVAL('person_seq'), 'Modene 1', 'Novi Sad', null, 'BB', 'test.2fa@mailinator.com', 'Entepreneur', 'Entrepreneur', null, null);
INSERT INTO public.auth (id, state_id, password, user_role_id, blocked, totp_secret, username, person_id) VALUES (NEXTVAL('auth_seq'), 3, '$2a$10$nTWQERaNUio88aEHzSVhrOmzsH6XRCfrftpJDxNqwsEdDjh8Y4PFi', 4, false, 'secret', 'test2fa', 14);
INSERT INTO public.temporary_token (id, expiration_time, temporary_token_type_id, value, auth_id) VALUES (NEXTVAL('temporary_token_seq'), TO_DATE('01/05/2050', 'DD/MM/YYYY'), 1, '2faToken', 14);
INSERT INTO public.authorized_action (id, auth_id, data, expiration, type_id) VALUES (NEXTVAL('authorized_action_seq'), 14, 'twoFactorAuthAction', TO_DATE('01/05/2050', 'DD/MM/YYYY'), 1);


INSERT INTO public.remember_me_cookie (id, expiration_time, value, auth_id) VALUES (2, TO_DATE('01/05/2022', 'DD/MM/YYYY'), '1234', 6);
INSERT INTO public.remember_me_cookie (id, expiration_time, value, auth_id) VALUES (3, TO_DATE('01/05/2022', 'DD/MM/YYYY'), '1234', 7);
INSERT INTO public.remember_me_cookie (id, expiration_time, value, auth_id) VALUES (4, TO_DATE('01/05/2022', 'DD/MM/YYYY'), '1234', 8);